#!/usr/bin/env tsx
/**
 * Interactive setup wizard for claw.
 * Run: pnpm run setup
 *
 * What it does:
 *   1. Reads claw.config.json to know how many Gmail accounts to prompt for
 *   2. Prompts for all required .env values
 *   3. Writes .env
 *   4. Generates a launchd plist (macOS only) and offers to bootstrap it
 */

import { createInterface } from 'node:readline/promises';
import { stdin as input, stdout as output } from 'node:process';
import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';

const rl = createInterface({ input, output });

async function ask(question: string, defaultValue = ''): Promise<string> {
  const hint = defaultValue ? ` [${defaultValue}]` : '';
  const answer = await rl.question(`  ${question}${hint}: `);
  return answer.trim() || defaultValue;
}

function header(title: string) {
  console.log(`\n── ${title} ${'─'.repeat(Math.max(0, 50 - title.length))}`);
}

async function main() {
  const clawDir = process.cwd();

  console.log('\n╔══════════════════════════════════╗');
  console.log('║        claw setup wizard         ║');
  console.log('╚══════════════════════════════════╝\n');
  console.log(`Working directory: ${clawDir}`);

  // ── Prerequisite: claw.config.json ────────────────────────────────────────
  const configPath = path.join(clawDir, 'claw.config.json');
  if (!fs.existsSync(configPath)) {
    console.error('\n[error] claw.config.json not found.');
    console.error('  Copy claw.config.example.json, fill in your repos and Gmail accounts, then re-run setup.\n');
    process.exit(1);
  }
  const clawConfig = JSON.parse(fs.readFileSync(configPath, 'utf-8')) as {
    repos: { channelName: string }[];
    gmail: { email: string; label: string }[];
  };
  console.log(`\nFound ${clawConfig.repos.length} repo(s) and ${clawConfig.gmail.length} Gmail account(s) in claw.config.json.`);

  // ── Auth ──────────────────────────────────────────────────────────────────
  header('Auth');
  console.log('  Claude Max subscription required. Get token with: claude setup-token');
  const CLAUDE_CODE_OAUTH_TOKEN = await ask('Claude OAuth token');
  const GH_TOKEN = await ask('GitHub PAT (repo + workflow scopes)');

  // ── Discord ───────────────────────────────────────────────────────────────
  header('Discord');
  console.log('  All IDs are snowflakes — enable Developer Mode in Discord to copy them.');
  const DISCORD_BOT_TOKEN = await ask('Bot token');
  const DISCORD_APPLICATION_ID = await ask('Application ID');
  const DISCORD_PUBLIC_KEY = await ask('Public key');
  const DISCORD_GUILD_ID = await ask('Guild (server) ID');
  const DISCORD_OWNER_USER_ID = await ask('Your Discord user ID');
  const DISCORD_CHANNEL_GENERAL = await ask('Channel ID — general (catch-all)');
  const DISCORD_CHANNEL_CLAW = await ask('Channel ID — claw self-maintenance');
  const DISCORD_CHANNEL_MAIL_ALERTS = await ask(
    'Channel ID — mail alerts (blank = same as general)',
    '',
  );

  // ── Gmail ─────────────────────────────────────────────────────────────────
  header('Gmail');
  const GMAIL_CLIENT_ID = await ask('OAuth client ID (from Google Cloud Console)');
  const GMAIL_CLIENT_SECRET = await ask('OAuth client secret');

  const gmailTokenLines: string[] = [];
  if (clawConfig.gmail.length > 0) {
    console.log('\n  Generate each refresh token with: tsx scripts/gmail-auth.ts <email>');
    for (let i = 0; i < clawConfig.gmail.length; i++) {
      const account = clawConfig.gmail[i];
      const token = await ask(`Refresh token for ${account.email} (${account.label})`);
      gmailTokenLines.push(`GMAIL_REFRESH_TOKEN_${i + 1}=${token}`);
    }
  }

  // ── Dashboard ─────────────────────────────────────────────────────────────
  header('Dashboard');
  const DASHBOARD_PORT = await ask('Port', '3200');
  const DASHBOARD_SECRET = await ask('Secret (min 8 chars)');

  // ── Paths ─────────────────────────────────────────────────────────────────
  header('Paths');
  const DATA_DIR = await ask('Data directory', path.join(clawDir, 'data'));
  const LOGS_DIR = await ask('Logs directory', path.join(clawDir, 'logs'));

  // ── Write .env ────────────────────────────────────────────────────────────
  const envLines = [
    '# Generated by `pnpm run setup`',
    '',
    '# ── Auth ────────────────────────────────────────────────────────',
    `CLAUDE_CODE_OAUTH_TOKEN=${CLAUDE_CODE_OAUTH_TOKEN}`,
    `GH_TOKEN=${GH_TOKEN}`,
    '',
    '# ── Discord ─────────────────────────────────────────────────────',
    `DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}`,
    `DISCORD_APPLICATION_ID=${DISCORD_APPLICATION_ID}`,
    `DISCORD_PUBLIC_KEY=${DISCORD_PUBLIC_KEY}`,
    `DISCORD_GUILD_ID=${DISCORD_GUILD_ID}`,
    `DISCORD_CHANNEL_GENERAL=${DISCORD_CHANNEL_GENERAL}`,
    `DISCORD_CHANNEL_CLAW=${DISCORD_CHANNEL_CLAW}`,
    `DISCORD_CHANNEL_MAIL_ALERTS=${DISCORD_CHANNEL_MAIL_ALERTS}`,
    `DISCORD_OWNER_USER_ID=${DISCORD_OWNER_USER_ID}`,
    '',
    '# ── Gmail ────────────────────────────────────────────────────────',
    `GMAIL_CLIENT_ID=${GMAIL_CLIENT_ID}`,
    `GMAIL_CLIENT_SECRET=${GMAIL_CLIENT_SECRET}`,
    ...gmailTokenLines,
    '',
    '# ── Polling ──────────────────────────────────────────────────────',
    `MAIL_POLL_INTERVAL_SEC=300`,
    '',
    '# ── Dashboard ────────────────────────────────────────────────────',
    `DASHBOARD_PORT=${DASHBOARD_PORT}`,
    `DASHBOARD_SECRET=${DASHBOARD_SECRET}`,
    '',
    '# ── Paths ────────────────────────────────────────────────────────',
    `DATA_DIR=${DATA_DIR}`,
    `LOGS_DIR=${LOGS_DIR}`,
  ];

  const envPath = path.join(clawDir, '.env');
  fs.writeFileSync(envPath, envLines.join('\n') + '\n');
  console.log(`\n✓ .env written to ${envPath}`);

  // ── launchd plist (macOS only) ────────────────────────────────────────────
  if (process.platform !== 'darwin') {
    console.log('\nNon-macOS platform — skipping launchd plist generation.');
    console.log('Start claw manually: pnpm build && pnpm start');
    rl.close();
    return;
  }

  header('macOS daemon (launchd)');
  const nodePath = process.execPath;
  const uid = execSync('id -u').toString().trim();
  const home = process.env['HOME'] ?? `/Users/${process.env['USER']}`;
  const plistLabel = 'com.claw';
  const plistDir = path.join(home, 'Library', 'LaunchAgents');
  const plistPath = path.join(plistDir, `${plistLabel}.plist`);

  // Build PATH: node's bin dir + common tool dirs + homebrew if present
  const nodeBinDir = path.dirname(nodePath);
  const extraDirs = ['/opt/homebrew/bin', '/usr/local/bin', `${home}/.local/bin`]
    .filter((d) => fs.existsSync(d))
    .join(':');
  const daemonPath = [nodeBinDir, extraDirs, '/usr/bin:/bin'].filter(Boolean).join(':');

  fs.mkdirSync(path.join(clawDir, 'logs'), { recursive: true });

  const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>${plistLabel}</string>
    <key>ProgramArguments</key>
    <array>
        <string>${nodePath}</string>
        <string>${path.join(clawDir, 'dist', 'server.js')}</string>
    </array>
    <key>WorkingDirectory</key>
    <string>${clawDir}</string>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>${daemonPath}</string>
        <key>HOME</key>
        <string>${home}</string>
    </dict>
    <key>StandardOutPath</key>
    <string>${path.join(clawDir, 'logs', 'launchd.log')}</string>
    <key>StandardErrorPath</key>
    <string>${path.join(clawDir, 'logs', 'launchd.error.log')}</string>
</dict>
</plist>`;

  fs.writeFileSync(plistPath, plist);
  console.log(`✓ Plist written to ${plistPath}`);
  console.log(`  node: ${nodePath}`);
  console.log(`  PATH: ${daemonPath}`);

  const doBootstrap = await ask('\nBootstrap daemon now? (y/n)', 'y');
  if (doBootstrap.toLowerCase() === 'y') {
    try {
      execSync(`launchctl bootstrap gui/${uid} "${plistPath}"`, { stdio: 'inherit' });
      console.log(`\n✓ Daemon registered. Next steps:`);
    } catch {
      console.log('\n  (Already loaded or bootstrap failed — continuing)');
    }
    console.log(`  1. pnpm run migrate`);
    console.log(`  2. pnpm build`);
    console.log(`  3. launchctl kickstart -k gui/${uid}/${plistLabel}`);
  } else {
    console.log(`\nTo start later:`);
    console.log(`  launchctl bootstrap gui/${uid} "${plistPath}"`);
    console.log(`  pnpm run migrate && pnpm build`);
    console.log(`  launchctl kickstart -k gui/${uid}/${plistLabel}`);
  }

  rl.close();
}

main().catch((e) => {
  console.error(e);
  rl.close();
  process.exit(1);
});
